config/routes.rb
Rails.application.routes.draw do
	# Root
	root 'basic_pages#home' #root_path

	# Basic Pages
  get '/about', to: 'basic_pages#about' #about_path
  get '/help',  to: 'basic_pages#help' #help_path

	# Users
	get  '/signup', to: 'users#new' #signup_path
	post '/signup', to: 'users#create' #signup_path
	resources :users
	#Controller Methods made available: show, edit, index, update, destroy
	#RESTful Equivalents respectively:  GET   GET   GET    PATCH   DELETE

	# Sessions (Login/Logout)
	get    '/login',  to: 'sessions#new'
	post   '/login',  to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	# Activation
	resources :account_activations, only: [:edit]

	# Password Reset
	resources :password_resets, only: [:new, :edit, :create, :update]

	#Projects
	resources :projects, only: [:create, :destroy, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :tasks, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token, :activation_token, :reset_token

	has_many :projects, dependent: :destroy

	before_save {email.downcase!}
	before_create :create_activation_digest

	validates :name, presence: true, length: {maximum: 60, minimum: 6}

	EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length:{maximum: 255}, format:{with: EMAIL_REGEX},
	uniqueness: {case_sensitive: false}

	has_secure_password
	validates :password, presence: true, length: {minimum: 6}, allow_nil: true

	# returns hash digest of string
	def self.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# generates random remember token
	def self.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		# update_attribute is updating a database column, the :remember_digest can be
		# found in one of the migrations. .remember_token is an attribute created by attr_accessor
		# it is local and doesnt exist in the database
		# we use the User.digest method to encrypt the token in the db
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		#Password.new retrieves the digest from the database.
		# .is_password method hashes the arguement passed to this function and compares it to the digest
		# the remember_token arguement in this method is NOT the attribute in this user, they just have the
		#same name.
		BCrypt::Password.new(digest).is_password?( token)
	end

	def activate
		update_columns(activated: true, activated_at: Time.zone.now)
	end

	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	def create_reset_digest
		self.reset_token = User.new_token
		update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
	end

	def send_reset_email
		UserMailer.password_reset(self).deliver_now
	end

	def password_reset_expired?
		reset_sent_at < 2.hours.ago
	end

	private
		def create_activation_digest
			self.activation_token  = User.new_token
			self.activation_digest = User.digest(activation_token)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only:[:index, :edit, :update, :destroy]
	before_action :correct_user, only:[:edit, :update]
	before_action :admin_user, only: [:destroy, :index]

	def show
		@user = User.find(params[:id])
		redirect_to root_url and return unless @user.activated?
		@projects = @user.projects.paginate(page: params[:page])
	end

	def new
		@user = User.new
  end

	def create
		@user = User.new(user_params)
		if @user.save
			@user.send_activation_email
			message = "Last step: check your email to activate your account. "
			message += "If you don't see it in your inbox, check your spam folder."
			flash[:info] = message
			redirect_to root_url
			#log_in @user
			#flash[:success] = "Signup successful. Welcome to Taskr!"
			#redirect_to @user
		else
			render 'new'
		end
	end

	def index
		@users = User.where(activated: true).paginate(page: params[:page])
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "user deleted"
		redirect_to users_url
	end

	private

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_url) unless current_user?(@user)
		end

		def admin_user
			redirect_to(root_url) unless current_user.admin?
		end
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, size: 80)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

end

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:form_url)) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<%= f.label :name %>
	<%= f.text_field :name, class: "form-control" %>

	<%= f.label :email %>
	<%= f.email_field :email, class: "form-control" %>

	<%= f.label :password %>
	<%= f.password_field :password, class: "form-control" %>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: "form-control" %>

	<%= f.submit yield(:btn_txt), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		 | <%= link_to 'delete', user, method: :delete, data:{confirm:'are you sure?'} %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Settings") %>
<% provide(:btn_txt, "Save changes") %>
<% provide(:form_url, user_path(@user)) %>

<h1>Edit user info</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'users/form' %>
		<div class="gravatar_edit">
			<%= gravatar_for @user %>
			<a href="http://gravatar.com/email" target="_blank" rel="noopen">change</a>
			<small>This wensite uses Gravatar. Click here to learn more</small>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Index") %>
<h1>Admin Eyes 0nly</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<% provide(:btn_txt, "Submit") %>
<% provide(:form_url, signup_path) %>

<h1>Sign up for Taskr</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'users/form' %>
		<p>Already have an account? <%= link_to "Log in here", login_path %></p>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
	<div class="col-md-8">
		<% if @user.projects.any? %>
			<h3>Projects (<%= @user.projects.count %>)</h3>
			<ol class="projects">
				<%= render @projects %>
			</ol>
			<%= will_paginate @projects %>
		<% end %>
	</div>
</div>