config/routes.rb
Rails.application.routes.draw do
	# Root
	root 'basic_pages#home' #root_path

	# Basic Pages
  get '/about', to: 'basic_pages#about' #about_path
  get '/help',  to: 'basic_pages#help' #help_path

	# Users
	get  '/signup', to: 'users#new' #signup_path
	post '/signup', to: 'users#create' #signup_path
	resources :users
	#Controller Methods made available: show, edit, index, update, destroy
	#RESTful Equivalents respectively:  GET   GET   GET    PATCH   DELETE

	# Sessions (Login/Logout)
	get    '/login',  to: 'sessions#new'
	post   '/login',  to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	# Activation
	resources :account_activations, only: [:edit]

	# Password Reset
	resources :password_resets, only: [:new, :edit, :create, :update]

	#Projects
	resources :projects, only: [:create, :destroy, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :tasks, only: [:create, :destroy]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
	default_scope -> {order(created_at: :desc)}
	validates :user_id, presence: true
	validates :title, presence: true, length:{maximum: 100}
	has_many :tasks, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]
	before_action :correct_user, only: :destroy

	def create
		@project = current_user.projects.build(project_params)
		if @project.save
			flash[:success] = "project created"
			redirect_to current_user
		else
			render 'basic_pages/home'
		end
	end

	def destroy
		@project.destroy
		flash[:success] = "Project deleted"
		redirect_to request.referrer || root_url
	end

	def show
		@project = Project.find(params[:id])
		@tasks = @project.tasks.paginate(page: params[:page])
		@task = @project.tasks.build
	end

	private
		def project_params
			params.require(:project).permit(:title)
		end

		def correct_user
			@project = current_user.projects.find_by(id: params[:id])
			redirect_to root_url if @project.nil?
		end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<li id="project-<%= project.id %>">
	<h3><span class="title"><%= link_to project.title, project_path(project) %></span></h3><br>
	<span class="timestamp">
		Posted <%= time_ago_in_words(project.created_at) %> ago
		<% if current_user?(project.user) %>
			<%= link_to "delete", project, method: :delete, data:{confirm: "are you sure?"} %>
		<% end %>
	</span>
</li>

app/views/projects/show.html.erb
<% provide(:title, @project.title) %>

<div class="col-md-8">
	<% if @project.tasks.any? %>
		<h4>Tasks (<%= @project.tasks.count %>)</h4>
		<ol class="tasks">
			<%= render @tasks %>
		</ol>
		<%= will_paginate @tasks %>
	<% end %>
</div>

<%= @project.user_id %>

<%= form_for(@task) do |f| %>
	<%= hidden_field_tag :project_id, @task.project_id %>

	<div class="field">
		<%= f.text_area :content, placeholder: "describe the task" %>
	</div>
	<%= f.submit "Add task", class: "btn btn-primary" %>
<% end %>