config/routes.rb
Rails.application.routes.draw do
	# Root
	root 'basic_pages#home' #root_path

	# Basic Pages
  get '/about', to: 'basic_pages#about' #about_path
  get '/help',  to: 'basic_pages#help' #help_path

	# Users
	get  '/signup', to: 'users#new' #signup_path
	post '/signup', to: 'users#create' #signup_path
	resources :users
	#Controller Methods made available: show, edit, index, update, destroy
	#RESTful Equivalents respectively:  GET   GET   GET    PATCH   DELETE

	# Sessions (Login/Logout)
	get    '/login',  to: 'sessions#new'
	post   '/login',  to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	# Activation
	resources :account_activations, only: [:edit]

	# Password Reset
	resources :password_resets, only: [:new, :edit, :create, :update]

	#Projects
	resources :projects, only: [:create, :destroy, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :tasks, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		This is an Oberlin Winter Term project by Charles McClain, you can find the source code <a href="https://github.com/SeaCDragon/taskr/">here</a>
	</small>
	<ul>
		<li><%= link_to "About", about_path %></li>
	</ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Taskr", root_path, id: "logo" %>
		<nav>
			<ul class = "nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<% if logged_in? %>
					<li><%= link_to "Profile", current_user %></li>
					<li><%= link_to "Settings", edit_user_path(current_user) %></li>
					<li><%= link_to "Logout", logout_path, method: :delete %></li>
					<% if current_user.admin? %>
						<li><%= link_to "INDEX", users_path %></li>
					<% end %>
				<% else %>
					<li><%= link_to "Log In", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<%= render 'layouts/header' %>
		<div class="container">

			<!-- flash messages -->
			<% flash.each do |message_type, message| #|key, value|%>
			 	<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
			<% end %>

			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
  </body>
</html>